import argparse
import os
import sys
import classifiers.rule_based as rb
import classifiers.ml_classifier_1 as ml1
import classifiers.ml_classifier_2 as ml2
import prompt as prompt

classifiers = {
    "rulebased": rb,
    "ml1": ml1,
    "ml2": ml2,
}

MODEL_PREFIX_TO_CLASSIFIER = {"MLP": "ml1", "LR": "ml2"}


def train_command(classifier_name, is_grouped, use_bert):
    return (
        f"python main.py train --classifier {classifier_name} "
        f"--grouped {'y' if is_grouped else 'n'} --bert {'y' if use_bert else 'n'}"
    )


def explain_missing_file(missing_path, action):
    path = os.path.normpath(str(missing_path or "")).replace(os.sep, "/")
    filename = os.path.basename(path)

    print(f"\nError: {action} failed because a required file is missing:")
    print(f"  {path or '<unknown file>'}\n")

    if path.endswith("data/raw/dialog_acts.dat"):
        print("This is the raw dialog acts dataset that everything else is built from.")
        print("Place the original 'dialog_acts.dat' file at data/raw/dialog_acts.dat, then run:")
        print("  python data_preprocess.py")
    elif path.endswith("data/raw/dialog_acts_test.dat"):
        print("This is the held-out test set used by the 'heldout' command.")
        print("It is not generated by this project. Place the provided held-out file at:")
        print("  data/raw/dialog_acts_test.dat")
    elif "data/processed/" in path:
        split = "grouped" if filename.startswith("grouped") else "original"
        print(f"This is the processed '{split}' train/test split, which has not been generated yet.")
        print("Create all processed splits by running:")
        print("  python data_preprocess.py")
        print("(this needs the raw dataset at data/raw/dialog_acts.dat)")
    elif filename.endswith(".joblib"):
        parts = filename[: -len(".joblib")].split("_")
        classifier_name = MODEL_PREFIX_TO_CLASSIFIER.get(parts[0], "<ml1|ml2>")
        model_bert = "bert" in parts
        model_grouped = "grouped" in parts
        kind = "vectorizer" if "vectorizer" in parts else "trained model"
        print(
            f"This is the {kind} for classifier '{classifier_name}' "
            f"(grouped={model_grouped}, bert={model_bert}), which has not been trained yet."
        )
        print("Train it with exactly these settings by running:")
        print(f"  {train_command(classifier_name, model_grouped, model_bert)}")
        print("(if training also fails, run 'python data_preprocess.py' first)")
    elif filename.startswith("restaurant_info"):
        print("This is the restaurant database used by the dialog system to look up suggestions.")
        print(f"Make sure '{filename}' exists at {path}.")
    else:
        print("Check that the file exists at the path above and that you are running")
        print("main.py from the project root directory.")


def ensure_files_exist(paths, action):
    for path in paths:
        if path and not os.path.exists(path):
            explain_missing_file(path, action)
            sys.exit(1)


def train_classifier(classifier_name, isGrouped, use_bert):
    classifier = classifiers[classifier_name]
    print(
        f"\nYou are training the {classifier.name} model with the following settings: grouped={isGrouped}, bert={use_bert}\n"
    )
    try:
        classifier.train(isGrouped=isGrouped, use_bert=use_bert)
    except FileNotFoundError as e:
        explain_missing_file(e.filename, f"Training '{classifier_name}'")
        sys.exit(1)


def test_classifier(classifier_name, isHeldOut, isGrouped, use_bert):
    classifier = classifiers[classifier_name]
    print(
        f"\nYou are testing the {classifier.name} model with the following settings: grouped={isGrouped}, bert={use_bert}, held-out:{isHeldOut}\n"
    )
    try:
        classifier.test(isHeldOut=isHeldOut, isGrouped=isGrouped, use_bert=use_bert)
    except FileNotFoundError as e:
        explain_missing_file(
            e.filename,
            f"{'Held-out testing' if isHeldOut else 'Testing'} '{classifier_name}'",
        )
        sys.exit(1)


def activate_prompt_with_classifier(classifier_name, is_grouped, use_bert):
    action = f"Starting the prompt with '{classifier_name}'"
    ensure_files_exist(prompt.get_model_paths(classifier_name, is_grouped, use_bert), action)
    try:
        prompt.manage(classifier_name, is_grouped, use_bert)
    except FileNotFoundError as e:
        explain_missing_file(e.filename, action)
        sys.exit(1)


# The dialog system always uses the MLP (ml1) trained on the grouped split
# with DistilBERT embeddings.
DIALOG_IS_GROUPED = True
DIALOG_USE_BERT = True
DIALOG_RESTAURANT_DB = "dialog/restaurant_info_extended.csv"


def activate_dialog_with_classifier(slot_fallback, reasoning_transparency, tts):
    action = "Starting the dialog system"
    ensure_files_exist(
        [*prompt.get_model_paths("ml1", DIALOG_IS_GROUPED, DIALOG_USE_BERT), DIALOG_RESTAURANT_DB],
        action,
    )
    try:
        import dialog.dialog_manager as dm

        dm.manage(DIALOG_IS_GROUPED, DIALOG_USE_BERT, slot_fallback, reasoning_transparency, tts)
    except FileNotFoundError as e:
        explain_missing_file(e.filename, action)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Restaurant dialog system")

    subparsers = parser.add_subparsers(dest="command", required=True)

    train_parser = subparsers.add_parser("train", help="Train a classifier")
    train_parser.add_argument(
        "--classifier",
        choices=classifiers.keys(),
        required=True,
    )
    train_parser.add_argument("--grouped", choices=["y", "n"], required=True)
    train_parser.add_argument("--bert", choices=["y", "n"], required=False, default="n")

    test_parser = subparsers.add_parser("test", help="Test a classifier")
    test_parser.add_argument(
        "--classifier",
        choices=classifiers.keys(),
        required=True,
    )
    test_parser.add_argument("--grouped", choices=["y", "n"], required=True)
    test_parser.add_argument("--bert", choices=["y", "n"], required=False, default="n")

    prompt_parser = subparsers.add_parser(
        "prompt", help="Start the prompt based classification system"
    )
    prompt_parser.add_argument(
        "--classifier",
        choices=classifiers.keys(),
        required=True,
    )
    prompt_parser.add_argument("--grouped", choices=["y", "n"], required=True)
    prompt_parser.add_argument(
        "--bert", choices=["y", "n"], required=False, default="n"
    )

    dialog_parser = subparsers.add_parser(
        "dialog", help="Start the restaurant dialog system"
    )
    dialog_parser.add_argument(
        "--slot-fallback",
        choices=["levenshtein", "semantic"],
        default="levenshtein",
        help="Slot extraction fallback method",
    )

    dialog_parser.add_argument(
        "--reasoning-transparency",
        choices=["y", "n"],
        default="y",
        help="Show or hide the reasoning behind the system's responses",
    )
    dialog_parser.add_argument(
        "--tts",
        choices=["y", "n"],
        default="n",
        help="Speak the system's utterances aloud",
    )

    heldout_parser = subparsers.add_parser("heldout", help="Held-out test set")
    heldout_parser.add_argument(
        "--classifier", choices=classifiers.keys(), required=True
    )
    heldout_parser.add_argument("--grouped", choices=["y", "n"], required=True)
    heldout_parser.add_argument(
        "--bert", choices=["y", "n"], required=False, default="n"
    )

    args = parser.parse_args()
    is_grouped = getattr(args, "grouped", None) == "y"
    use_bert = getattr(args, "bert", None) == "y"

    if args.command == "train":
        train_classifier(args.classifier, is_grouped, use_bert)
    elif args.command == "test":
        test_classifier(
            args.classifier, isHeldOut=False, isGrouped=is_grouped, use_bert=use_bert
        )
    elif args.command == "prompt":
        activate_prompt_with_classifier(args.classifier, is_grouped, use_bert)
    elif args.command == "dialog":
        activate_dialog_with_classifier(
            args.slot_fallback, args.reasoning_transparency == "y", args.tts == "y"
        )
    elif args.command == "heldout":
        test_classifier(
            args.classifier, isHeldOut=True, isGrouped=is_grouped, use_bert=use_bert
        )


if __name__ == "__main__":
    main()
